# Generated by Django 4.2.5 on 2023-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('cargo', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=250)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proventos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquidos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
