# Generated by Django 4.2.5 on 2023-09-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
