# Generated by Django 4.2.5 on 2023-09-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataTable', '0002_remove_funcionario_cargo_alter_salario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataTable.cargo'),
        ),
    ]
