# Generated by Django 4.2.5 on 2023-09-15 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataTable', '0003_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salario', to='DataTable.funcionario'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
